# Generated by Django 4.2.7 on 2023-11-02 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='viewer',
            old_name='address',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='viewer',
            old_name='fullname',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='viewer',
            name='mobile',
        ),
    ]
