# Generated by Django 4.2.7 on 2023-11-02 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_address_viewer_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewer',
            name='username',
            field=models.CharField(max_length=40),
        ),
    ]
